#!/bin/bash

echo 'TRAVIS_REPO_SLUG='$TRAVIS_REPO_SLUG
echo 'TRAVIS_JDK_VERSION='$TRAVIS_JDK_VERSION
echo 'TRAVIS_PULL_REQUEST='$TRAVIS_PULL_REQUEST
echo 'TRAVIS_BRANCH='$TRAVIS_BRANCH
echo 'HOME='$HOME
echo 'GH_TOKEN='${GH_TOKEN}
echo 'TRAVIS_BUILD_NUMBER='$TRAVIS_BUILD_NUMBER
